У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tip.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
print('Перші 5 рядків')
df.head()

Перші 5 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
print('Розмір датасету (shape)')
df.shape

Розмір датасету (shape)

(244, 7)

In [8]:
print('Назви всіх колонок')
df.columns

Назви всіх колонок

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
print('Інформацію про типи даних (info)')
df.info()

Інформацію про типи даних (info)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [12]:
total_bill = df['total_bill']
print('Колонка total_bill (загальний рахунок)')
total_bill

Колонка total_bill (загальний рахунок)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [14]:
bill_and_tips = df[['total_bill','tip']]
print('Колонки total_bill та tip (чайові) разом')
bill_and_tips

Колонки total_bill та tip (чайові) разом

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [21]:
print('Перші 10 рядків')
df.iloc[0:10]
#df.head(10)

Перші 10 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [22]:
print('Рядок з індексом 5')
df.loc[5]

Рядок з індексом 5

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [26]:
print('Всі рахунки більше 20 доларів')
bill_more_20 = df[df['total_bill'] > 20]
display(bill_more_20.shape) 
bill_more_20.head()

Всі рахунки більше 20 доларів

(97, 7)

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [27]:
print('Всі відвідувачі-жінки')
female_visitor = df[df['sex'] == 'Female']
display(female_visitor.shape) 
female_visitor.head()

Всі відвідувачі-жінки

(87, 7)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [28]:
print('Рахунки на вечерю')
dinner_bill = df[df['time'] == 'Dinner']
display(dinner_bill.shape) 
dinner_bill.head()

Рахунки на вечерю

(176, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
print('Рахунки на вечерю з сумою чеку більше 30 доларів')
dinner_more_30 = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]
display(dinner_more_30.shape) 
dinner_more_30.head()

Рахунки на вечерю з сумою чеку більше 30 доларів

(27, 7)

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [53]:
mean_bill = df['total_bill'].mean()
max_tip = df['tip'].max()
isnull_count = df.isna().sum()
dinner_lunch_bill = df.groupby('time').size()

print(f'Середній розмір рахунку на всьому наборі даних: {mean_bill}\n')
print(f'Максимальні чайові: {max_tip}\n')
print(f'Кількість пропущених значень у всіх колонках: \n{isnull_count}\n')
print(f'Скільки в наборі даних рахунків за обіди і за вечері: \n{dinner_lunch_bill}')

# df['time'].unique()

Середній розмір рахунку на всьому наборі даних: 19.78594262295082

Максимальні чайові: 10.0

Кількість пропущених значень у всіх колонках:
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

Скільки в наборі даних рахунків за обіди і за вечері:
time
Dinner    176
Lunch      68
dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [58]:
bill_by_sex = df.groupby('sex')['total_bill'].mean()
tip_by_day = df.groupby('day')['tip'].mean()
visitor_by_day = df.groupby('day')['size'].sum()

print(f'Середній рахунок за статтю: \n{bill_by_sex}\n')
print(f'Середні чайові за днем тижня: \n{tip_by_day}\n')
print(f'Скільки відвідувачів у кожен день: \n{visitor_by_day}\n')

Середній рахунок за статтю:
sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

Середні чайові за днем тижня:
day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

Скільки відвідувачів у кожен день:
day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [64]:
df['tip_percentage'] = (df['tip'] / df['total_bill']).round(4)
df['tip_percentage, %'] = (df['tip'] / df['total_bill'] *100).round(2)
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,"tip_percentage, %"
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0594,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,0.1605,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,0.1666,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,0.1398,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,0.1468,14.68
5,25.29,4.71,Male,No,Sun,Dinner,4,0.1862,18.62
6,8.77,2.00,Male,No,Sun,Dinner,2,0.2281,22.81
7,26.88,3.12,Male,No,Sun,Dinner,4,0.1161,11.61
8,15.04,1.96,Male,No,Sun,Dinner,2,0.1303,13.03
9,14.78,3.23,Male,No,Sun,Dinner,2,0.2185,21.85

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [68]:
print('За розміром рахунку (зростання)')
df.sort_values('total_bill', ascending=True).head(10)

За розміром рахунку (зростання)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,"tip_percentage, %"
67,3.07,1.00,Female,Yes,Sat,Dinner,1,0.3257,32.57
92,5.75,1.00,Female,Yes,Fri,Dinner,2,0.1739,17.39
111,7.25,1.00,Female,No,Sat,Dinner,1,0.1379,13.79
172,7.25,5.15,Male,Yes,Sun,Dinner,2,0.7103,71.03
149,7.51,2.00,Male,No,Thur,Lunch,2,0.2663,26.63
195,7.56,1.44,Male,No,Thur,Lunch,2,0.1905,19.05
218,7.74,1.44,Male,Yes,Sat,Dinner,2,0.1860,18.60
145,8.35,1.50,Female,No,Thur,Lunch,2,0.1796,17.96
135,8.51,1.25,Female,No,Thur,Lunch,2,0.1469,14.69
126,8.52,1.48,Male,No,Thur,Lunch,2,0.1737,17.37

In [69]:
print('За чайовими (спадання)')
df.sort_values('tip', ascending=False).head(10)

За чайовими (спадання)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,"tip_percentage, %"
170,50.81,10.00,Male,Yes,Sat,Dinner,3,0.1968,19.68
212,48.33,9.00,Male,No,Sat,Dinner,4,0.1862,18.62
23,39.42,7.58,Male,No,Sat,Dinner,4,0.1923,19.23
59,48.27,6.73,Male,No,Sat,Dinner,4,0.1394,13.94
141,34.30,6.70,Male,No,Thur,Lunch,6,0.1953,19.53
214,28.17,6.50,Female,Yes,Sat,Dinner,3,0.2307,23.07
183,23.17,6.50,Male,Yes,Sun,Dinner,4,0.2805,28.05
47,32.40,6.00,Male,No,Sun,Dinner,4,0.1852,18.52
239,29.03,5.92,Male,No,Sat,Dinner,3,0.2039,20.39
88,24.71,5.85,Male,No,Thur,Lunch,2,0.2367,23.67

In [70]:
print('топ-5 найбільших чайових (nlargest)')
df.nlargest(5, 'tip')

топ-5 найбільших чайових (nlargest)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,"tip_percentage, %"
170,50.81,10.00,Male,Yes,Sat,Dinner,3,0.1968,19.68
212,48.33,9.00,Male,No,Sat,Dinner,4,0.1862,18.62
23,39.42,7.58,Male,No,Sat,Dinner,4,0.1923,19.23
59,48.27,6.73,Male,No,Sat,Dinner,4,0.1394,13.94
141,34.30,6.70,Male,No,Thur,Lunch,6,0.1953,19.53